name: Bug Report
description: File a bug report to help us improve Aura CLI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
  - type: input
    id: version
    attributes:
      label: Aura CLI Version
      description: What version of Aura CLI are you running?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (other)
        - Other
    validations:
      required: true
      
  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using? (if building from source)
      placeholder: "go version go1.21.0"
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Navigate to '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell
      
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Any relevant configuration (remove sensitive information)
      render: yaml
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have removed any sensitive information from logs/config
          required: true